apiVersion: v1
kind: Service
metadata:
  name: projetos-datalake-coinmarketcap-service
spec:
  selector:
    app: projetos-datalake-coinmarketcap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
